# Generated by Django 3.2.4 on 2021-06-15 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('qualification', models.TextField()),
                ('consulting_time', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='doctor_image')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.department')),
            ],
        ),
    ]
