# Generated by Django 3.2.4 on 2021-06-15 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='image',
        ),
    ]
