# Generated by Django 3.2.4 on 2021-06-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0002_remove_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, default='doc.jpeg', upload_to='doctor_image'),
        ),
    ]
