# Generated by Django 3.2.4 on 2021-06-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0004_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name_plural': 'Banners'},
        ),
    ]
