# Generated by Django 3.2.4 on 2021-06-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0005_auto_20210617_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='consulting_time',
        ),
        migrations.AddField(
            model_name='doctor',
            name='consulting_time',
            field=models.ManyToManyField(to='hosp_app.ConsultTime'),
        ),
    ]
