# Generated by Django 3.2.4 on 2021-06-17 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0006_auto_20210617_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={},
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mob_no', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('date', models.DateField()),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.department')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.doctor')),
            ],
        ),
    ]
